/** @format */

export default {
  CREATE_MOD: "CREATE_MOD",
  SET_INSTANCE_TYPE: "SET_INSTANCE_TYPE",
  SET_INSTANCE_DETAILS: "SET_INSTANCE_DETAILS",
  SET_EKS_BREADCRUMP_TYPE: "SET_EKS_BREADCRUMP_TYPE",
  SET_FORMS_PAGE_NO: "SET_FORMS_PAGE_NO",
};
